//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//::                                                                         ::
//::     Antonio Manuel Rodrigues Manso                                      ::
//::                                                                         ::
//::     I N S T I T U T O    P O L I T E C N I C O   D E   T O M A R        ::
//::     Escola Superior de Tecnologia de Tomar                              ::
//::     e-mail: manso@ipt.pt                                                ::
//::     url   : http://orion.ipt.pt/~manso                                  ::
//::                                                                         ::
//::     This software was build with the purpose of investigate and         ::
//::     learning.                                                           ::
//::                                                                         ::
//::                                                               (c)2020   ::
//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//////////////////////////////////////////////////////////////////////////////
package Election.gui;

import Election.core.Election;
import Election.wallet.User;
import java.time.YearMonth;
import javax.swing.JComboBox;

/**
 *
 * @author manso
 */
public class Administration extends javax.swing.JFrame {
    public static String fileElection = "Election.obj";
    Election election;
    private User user;
    
    /**
     * Creates new form TemplarCoinGUI
     * @param user
     */
    
    
    private void atualizarDias() {
        // Obtém o número de dias do mês selecionado
        String mesSelecionado = startMonthComboBox.getSelectedItem().toString();
        String anoSelecionado = startYearComboBox.getSelectedItem().toString();
        String diaSelecionado = startDayComboBox.getSelectedItem().toString();
        int numeroDias = YearMonth.of(Integer.valueOf(anoSelecionado), Integer.valueOf(mesSelecionado)).lengthOfMonth();
        int selectedDayIndex = startDayComboBox.getSelectedIndex();
        // Popula o JComboBox de dias com os números de 1 ao número de dias do mês
        String[] dias = new String[numeroDias];
        for (int i = 0; i < numeroDias; i++) {
            dias[i] = String.valueOf(i + 1);
        }

        // Remove os itens antigos e adiciona os novos
        startDayComboBox.removeAllItems();
        for (String dia : dias) {
            startDayComboBox.addItem(dia);
        }
        
        // Mantém o dia selecionado se existir na nova lista
        if (selectedDayIndex >= 0 && selectedDayIndex < numeroDias) {
            startDayComboBox.setSelectedIndex(selectedDayIndex);
        }
    }
    
    public Administration(User user) {
        //Init GUI
        initComponents();
        atualizarDias();
        
        //Init Election
        election = new  Election();
        this.user = user;
        try {
            election = Election.load(fileElection);
        } catch (Exception e) {
        }
        
        setSize(800, 600);
        setLocationRelativeTo(null);   
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpElection = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton_NewElection = new javax.swing.JButton();
        jTextField_ElectionName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        startDayComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        startMonthComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        startYearComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        startDayComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        startMonthComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        startYearComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Election App");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpElection.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpElectionStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_NewElection.setText("Nova Eleição");
        jPanel1.add(jButton_NewElection, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));
        jPanel1.add(jTextField_ElectionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Candidatos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 180, -1));

        jButton1.setText("Add Candidate");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 210, 180));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Candidato");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Candidatos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 210, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 600, 260));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nome da Eleição");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fim da Eleição");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 20));

        startDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel3.add(startDayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 50, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("/");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 20, 20));

        startMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        startMonthComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                startMonthComboBoxItemStateChanged(evt);
            }
        });
        startMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMonthComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(startMonthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 50, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("/");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 20, 20));

        startYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", " " }));
        jPanel3.add(startYearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 70, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 380, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Inicio da Eleição");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 20));

        startDayComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel4.add(startDayComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 50, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("/");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 20, 20));

        startMonthComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        startMonthComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                startMonthComboBox1ItemStateChanged(evt);
            }
        });
        startMonthComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMonthComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(startMonthComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 50, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("/");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 20, 20));

        startYearComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", " " }));
        jPanel4.add(startYearComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 70, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 350, 30));

        tpElection.addTab("Eleições", jPanel1);

        getContentPane().add(tpElection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1386, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpElectionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpElectionStateChanged
        /*if( tpElection.getSelectedComponent()== pnUsersBalance){
            DefaultListModel model = new DefaultListModel();
            model.addAll(election.getCandidateVotes());
        }*/
    }//GEN-LAST:event_tpElectionStateChanged

    private void startMonthComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_startMonthComboBoxItemStateChanged
        // TODO add your handling code here:
        atualizarDias();
    }//GEN-LAST:event_startMonthComboBoxItemStateChanged

    private void startMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMonthComboBoxActionPerformed
        // TODO add your handling code here:
        atualizarDias();
    }//GEN-LAST:event_startMonthComboBoxActionPerformed

    private void startMonthComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_startMonthComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_startMonthComboBox1ItemStateChanged

    private void startMonthComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMonthComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startMonthComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ElectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ElectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ElectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ElectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ElectionGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_NewElection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_ElectionName;
    private javax.swing.JComboBox<String> startDayComboBox;
    private javax.swing.JComboBox<String> startDayComboBox1;
    private javax.swing.JComboBox<String> startMonthComboBox;
    private javax.swing.JComboBox<String> startMonthComboBox1;
    private javax.swing.JComboBox<String> startYearComboBox;
    private javax.swing.JComboBox<String> startYearComboBox1;
    private javax.swing.JTabbedPane tpElection;
    // End of variables declaration//GEN-END:variables
}
